apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nodejs-webapp
  template:
    metadata:
      labels:
        app: simple-nodejs-webapp
    spec:
      containers:
      - name: simple-nodejs-webapp
        image: yassinelasri/simple-nodejs-webapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
